import React, { useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  FlatList,
  SafeAreaView,
} from "react-native";
import { AntDesign } from "@expo/vector-icons"; // For expansion indicator
import Header from "../components/Header";
import { LinearGradient } from "expo-linear-gradient"; // Import gradientt
import Footer from "../components/Footer";

const categories = [
  {
    title: "United States Congress",
    agencies: [
      "Congressional Budget Office (CBO)",
      "Government Accountability Office (GAO)",
      "Government Publishing Office (USGPO)",
      "Office of Congressional Accessibility Services (OCAS)",
      "Office of the Attending Physician (OAP)",
      "Office of Congressional Workplace Rights (OCWR)",
      "Capitol Police Board (governing the United States Capitol Police - USCP)",
      "Architect of the Capitol (AOC)",
      "Capitol Visitor Center (CVC)",
      "United States Botanic Garden (USBG)",
      "Library of Congress (LOC)",
      "Global Legal Information Network (GLIN)",
      "Congressional Research Service (CRS)",
      "United States Copyright Office (USCO)",
      "Copyright Royalty Board (CRB)",
      "National Library Service for the Blind and Print Disabled",
    ],
  },
  {
    title: "Federal Judiciary of the United States",
    agencies: [
      "Supreme Court",
      "Circuit Courts of Appeals",
      "District Courts",
      "Judicial Panel on Multidistrict Litigation",
      "Court of International Trade",
      "Foreign Intelligence Surveillance Court",
      "Foreign Intelligence Surveillance Court of Review",
      "Alien Terrorist Removal Court",
      "United States Bankruptcy Courts",
      { type: "separator", label: "JUDICIAL BRANCH AGENCIES" },
      "Federal Judicial Center",
      "Federal Public Defender Organizations",
      "Judicial Conference of the United States",
      "Administrative Office of the United States Courts",
      "Office of Court Administration",
      "Office of Defender Services",
      "Office of Facilities and Security",
      "Office of Finance and Budget",
      "Office of the General Counsel",
      "Office of Human Resources",
      "Office of Information Technology",
      "Office of Internal Services",
      "Office of the Judicial Conference Executive Secretariat",
      "Office of Legislative Affairs",
      "Office of Judges Programs",
      "Probation and Pretrial Services System",
      "Office of Public Affairs",
      "Marshal of the United States Supreme Court",
      "Supreme Court Police",
      "United States Sentencing Commission",
    ],
  },
  {
    title: "Executive Office of the President",
    agencies: [
      "Office of the Chief of Staff",
      "Office of the National Security Advisor",
      "Domestic Policy Council",
      "National Economic Council",
      "Office of Cabinet Affairs",
      "Office of Communications",
      "Office of Digital Strategy",
      "Office of the First Lady",
      "Office of Intergovernmental Affairs",
      "Office of Legislative Affairs",
      "Office of Management and Administration",
      "Office of Political Affairs",
      "Office of the Staff Secretary",
      "Office of Records Management",
      "Office of Presidential Advance",
      "Presidential Personnel Office",
      "Office of Public Engagement",
      "Office of the Social Secretary",
      "White House Press Office",
      "Office of White House Counsel",
      "Oval Office Operations",
      { type: "separator", label: "WHITE HOUSE OFFICES & OPERATIONS" },
      "White House Military Office",
      "President's Commission on White House Fellowships",
    ],
  },
  {
    title: "United States Department of Agriculture (USDA)",
    agencies: [
      "Office of the Secretary of Agriculture",
      "Office of the Assistant Secretary for Congressional Relations",
      "Office of the Assistant Secretary for Civil Rights",
      "Office of the Assistant Secretary for Administration",
      "Office of Tribal Relations (OTR)",
      "Departmental Administration (DA)",
      "Office of Customer Experience",
      "Office of Contracting and Procurement (OCP)",
      "Office of Homeland Security (OHS)",
      "Office of Human Resources Management (OHRM)",
      "Office of Operations (OO)",
      "Office of Property and Environmental Management (OPEM)",
      "Office of Safety, Security and Protection (OSSP)",
      "Office of Small and Disadvantaged Business Utilization (OSDBU)",
      "Agriculture Buildings and Facilities (AgBF)",
      "Hazardous Materials Management (HMM)",
      "Office of Budget and Program Analysis (OBPA)",
      "Office of Communications (OC)",
      "Office of Ethics (OE)",
      "Office of Hearings and Appeals (OHA)",
      "National Appeals Division (NAD)",
      "Office of Administrative Law Judges (OALJ)",
      "Office of the Judicial Officer (OJO)",
      "Office of Inspector General (OIG)",
      "Office of Partnerships and Public Engagement (OPPE)",
      "Center for Faith-Based and Neighborhood Partnerships (CFBNP)",
      "Office of the Chief Economist (OCE)",
      "World Agricultural Outlook Board",
      "Office of the Chief Financial Officer (OFCO)",
      "National Finance Center (NFC)",
      "Office of the Chief Information Officer (OCIO)",
      "Office of the Executive Secretariat (OES)",
      "Office of the General Counsel (OGC)",
      "Office of Information Affairs",

      { type: "separator", label: "USDA FARM PRODUCTION & CONSERVATION" },
      "Under Secretary of Agriculture for Farm Production and Conservation (FPAC)",
      "Farm Service Agency (FSA)",
      "Commodity Credit Corporation (CCC)",
      "Natural Resources Conservation Service (NRCS)",
      "Risk Management Agency (RMA)",
      "Federal Crop Insurance Corporation (FCIC)",
      "Farm Production and Conservation Business Center (FBC)",

      { type: "separator", label: "USDA FOOD, NUTRITION & CONSUMER SERVICES" },
      "Under Secretary of Agriculture for Food, Nutrition, and Consumer Services (FNCS)",
      "Food and Nutrition Service (FNS)",
      "Center for Nutrition Policy and Promotion (CNPP)",

      { type: "separator", label: "USDA FOOD SAFETY" },
      "Under Secretary of Agriculture for Food Safety",
      "Food Safety and Inspection Service",

      { type: "separator", label: "USDA MARKETING & REGULATORY PROGRAMS" },
      "Under Secretary of Agriculture for Marketing and Regulatory Programs (MRP)",
      "Agricultural Marketing Service (AMS)",
      "Federal Grain Inspection Service (FGIS)",
      "Animal and Plant Health Inspection Service (APHIS)",
      "Plant Protection and Quarantine (PPQ)",
      "Wildlife Services (WS)",

      { type: "separator", label: "USDA NATURAL RESOURCES & ENVIRONMENT" },
      "Under Secretary of Agriculture for Natural Resources and Environment (NRE)",
      "United States Forest Service (USFS)",
      "International Institute of Tropical Forestry",

      { type: "separator", label: "USDA RESEARCH, EDUCATION & ECONOMICS" },
      "Under Secretary of Agriculture for Research, Education, and Economics (REE)",
      "Agricultural Research Service (ARS)",
      "National Agricultural Library (NAL)",
      "Economic Research Service (ERS)",
      "National Agricultural Statistics Service (NASS)",
      "National Institute of Food and Agriculture (NIFA)",
      "Office of the Chief Scientist",

      { type: "separator", label: "USDA RURAL DEVELOPMENT" },
      "Under Secretary of Agriculture for Rural Development (RD)",
      "Rural Development",
      "Rural Business-Cooperative Service (RBCS)",
      "Rural Housing Service (RHS)",
      "Rural Utilities Service (RUS)",

      { type: "separator", label: "USDA TRADE & FOREIGN AGRICULTURAL AFFAIRS" },
      "Under Secretary of Agriculture for Trade and Foreign Agricultural Affairs (TFAA)",
      "Foreign Agricultural Service (FAS)",
    ],
  },
  {
    title: "United States Department of Commerce (DOC)",
    agencies: [
      "Office of the Secretary (OS)",
      "Office of the Deputy Secretary",
      "Office of Public Engagement (OPE)",
      "Office of the Chief Financial Officer and Assistant Secretary for Administration (CFO/ASA)",
      "Office of Chief Information Officer (OCIO)",
      "Office of Executive Secretariat",
      "Office of General Counsel (OGC)",
      "Office of Legislative and Intergovernmental Affairs (OLIA)",
      "Office of Policy and Strategic Planning (OPSP)",
      "Office of Public Affairs (OPA)",
      "Office of Security (OSY)",
      "Office of the White House Liaison (OWHL)",
      "Office of Inspector General (OIG)",

      { type: "separator", label: "COMMERCE ECONOMIC & BUSINESS DEVELOPMENT" },
      "Economic Development Administration (EDA)",
      "Minority Business Development Agency (MBDA)",
      "National Technical Information Service (NTIS)",
      "National Telecommunications and Information Administration (NTIA)",
      "Institute for Telecommunication Sciences (ITS)",
      "First Responder Network Authority (FirstNet)",

      { type: "separator", label: "COMMERCE INDUSTRY & SECURITY" },
      "Under Secretary of Commerce for Industry and Security/Bureau of Industry and Security (BIS)",
      "Office of the Assistant Secretary for Export Administration",
      "Operating Committee for Export Policy (OC)",
      "Office of Strategic Industries and Economic Security",
      "Office of Nonproliferation and Treaty Compliance",
      "Office of National Security and Technology Transfer Controls",
      "Office of Exporter Services",
      "Office of Technology Evaluation",
      "Office of Export Enforcement (OEE)",

      { type: "separator", label: "COMMERCE ECONOMIC AFFAIRS" },
      "Under Secretary of Commerce for Economic Affairs (OUS/EA)",
      "Bureau of Economic Analysis (BEA)",
      "United States Census Bureau",

      { type: "separator", label: "COMMERCE INTELLECTUAL PROPERTY" },
      "Under Secretary of Commerce for Intellectual Property/United States Patent and Trademark Office (USPTO)",
      "Trademark Official Gazette",
      "Patent Trial and Appeal Board",
      "Trademark Trial and Appeal Board",
      "Office of the Commissioner of Patents",
      "Office of the Commissioner of Trademarks",

      { type: "separator", label: "COMMERCE INTERNATIONAL TRADE" },
      "Under Secretary of Commerce for International Trade/International Trade Administration (ITA)",
      "United States Commercial Service (CS)",

      { type: "separator", label: "COMMERCE OCEANS & ATMOSPHERE" },
      "Under Secretary of Commerce for Oceans and Atmosphere/National Oceanic and Atmospheric Administration (NOAA)",
      "Alliance for Coastal Technologies",
      "National Environmental Satellite, Data, and Information Service (NESDIS)",
      "National Marine Fisheries Service (NMFS)",
      "NOAA Fisheries Office of Law Enforcement",
      "National Ocean Service (NOS)",
      "National Weather Service (NWS)",
      "National Hurricane Center",
      "National Geodetic Survey (NGS)",
      "Office of Marine and Aviation Operations (OMAO)",
      "NOAA Commissioned Officer Corps",
      "Office of Oceanic and Atmospheric Research (OAR)",

      { type: "separator", label: "COMMERCE STANDARDS & TECHNOLOGY" },
      "Under Secretary of Commerce for Standards and Technology",
      "National Institute of Standards and Technology (NIST)",
    ],
  },
  {
    title: "United States Department of Defense (DOD)",
    agencies: [
      "Office of the Secretary of Defense (OSD)",
      "The Secretary of Defense",
      "The Deputy Secretary of Defense",
      "Office of the Under Secretary of Defense for Research and Engineering",
      "Office of the Under Secretary of Defense for Acquisition and Sustainment",
      "Office of the Under Secretary of Defense for Policy",
      "Office of the Under Secretary of Defense (Comptroller)/Chief Financial Officer of the Department of Defense",
      "Office of the Under Secretary of Defense for Personnel and Readiness",
      "Office of the Under Secretary of Defense for Intelligence and Security",
      "Office of the General Counsel of the Department of Defense",
      "Office of the Director, Cost Assessment and Program Evaluation",
      "Office of the Director, Operational Test and Evaluation",
      "Office of the Chief Information Officer of the Department of Defense",
      "Office of the Assistant Secretary of Defense for Legislative Affairs",
      "Office of the Assistant Secretary of Defense for Special Operations and Low-Intensity Conflict",
      "Office of the Assistant to the Secretary of Defense for Public Affairs",
      "Office of the Assistant to the Secretary of Defense for Privacy, Civil Liberties, and Transparency",
      "Office of the Director of Administration and Management",
      "Office of Net Assessment",

      { type: "separator", label: "DEFENSE AGENCIES" },
      "Defense Advanced Research Projects Agency (DARPA)",
      "Defense Commissary Agency (DeCA)",
      "Defense Contract Audit Agency (DCAA)",
      "Defense Contract Management Agency (DCMA)",
      "Defense Counterintelligence and Security Agency (DCSA)",
      "Defense Finance and Accounting Service (DFAS)",
      "Defense Health Agency (DHA)",
      "Defense Information Systems Agency (DISA)",
      "Defense Manpower Data Center (DMDC)",
      "Defense Legal Services Agency (DLSA)",
      "Defense Logistics Agency (DLA)",
      "Defense POW/MIA Accounting Agency (DPMAA)",
      "Defense Security Cooperation Agency (DSCA)",
      "Defense Threat Reduction Agency (DTRA)",
      "Missile Defense Agency (MDA)",
      "Pentagon Force Protection Agency (PFPA)",

      { type: "separator", label: "NATIONAL INTELLIGENCE AGENCIES" },
      "Defense Intelligence Agency (DIA)",
      "National Geospatial-Intelligence Agency (NGA)",
      "National Reconnaissance Office (NRO)",
      "National Security Agency/Central Security Service (NSA/CSS)",

      { type: "separator", label: "DEFENSE FIELD ACTIVITIES" },
      "Defense Media Activity (DMA)",
      "Defense Technical Information Center (DTIC)",
      "Defense Technology Security Administration (DTSA)",
      "Department of Defense Education Activity (DoDEA)",
      "Department of Defense Human Resources Activity (DoDHRA)",
      "Department of Defense Test Resource Management Center (DODTRMC)",
      "Office of Local Defense Community Cooperation (OLDCC)",
      "Washington Headquarters Services (WHS)",

      { type: "separator", label: "UNIVERSITIES & RESEARCH INSTITUTES" },
      "Defense Acquisition University (DAU)",
      "Uniformed Services University of the Health Sciences",
      "Armed Forces Radiobiology Research Institute",
      "National Defense University (NDU)",
      "National War College (NWC)",
      "Joint Forces Staff College (JFSC)",
      "National Intelligence University",
      "Dwight D. Eisenhower School for National Security and Resource Strategy",
      "College of International Security Affairs (CISA)",
      "College of Information and Cyberspace (CIC)",
      "Institute for National Strategic Studies (INSS)",

      { type: "separator", label: "UNIFIED COMBATANT COMMANDS" },
      "United States Africa Command (USAFRICOM)",
      "United States Central Command (USCENTCOM)",
      "United States Northern Command (USNORTHCOM)",
      "United States European Command (USEUCOM)",
      "United States Indo-Pacific Command (USINDOPACOM)",
      "United States Southern Command (USSOUTHCOM)",
      "United States Space Command (USSPACECOM)",
      "United States Special Operations Command (USSOCOM)",
      "United States Strategic Command (USSTRATCOM)",
      "United States Cyber Command (USCYBERCOM)",
      "United States Transportation Command (USTRANSCOM)",

      { type: "separator", label: "JOINT AGENCIES" },
      "Joint Chiefs of Staff",
      "National Guard Bureau",
      "Joint Personnel Recovery Agency",
      "Office of Military Commissions",
      "Court of Military Commission Review",
      "Armed Services Board of Contract Appeals",
      "Army and Air Force Exchange Service",
      "White House Military Office",
      "United States Military Entrance Processing Command",
      "Defense Microelectronics Activity",

      { type: "separator", label: "DEPARTMENT OF THE ARMY" },
      "Office of the Secretary of the Army",
      "Office of the Under Secretary of the Army",
      "Office of the Assistant Secretary of the Army for Civil Works",
      "Office of the Assistant Secretary of the Army for Acquisition, Logistics and Technology",
      "Office of the Assistant Secretary of the Army for Financial Management and Comptroller",
      "Office of the Assistant Secretary of the Army for Installations, Energy and Environment",
      "Office of the Assistant Secretary of the Army for Manpower and Reserve Affairs",
      "Office of the Administrative Assistant to the Secretary of the Army",
      "Office of the General Counsel of the Army",
      "Office of the Chief of Staff of the Army",
      "Chief of Staff of the United States Army",

      { type: "separator", label: "DEPARTMENT OF THE NAVY" },
      "Office of the Secretary of the Navy",
      "Office of the Under Secretary of the Navy",
      "Office of the Assistant Secretary of the Navy for Research, Development and Acquisition",
      "Office of the Assistant Secretary of the Navy for Manpower and Reserve Affairs",
      "Office of the Assistant Secretary of the Navy for Financial Management and Comptroller",
      "Office of the Assistant Secretary of the Navy for Installations and Environment",
      "Office of the General Counsel of the Navy",
      "Office of the Naval Inspector General",
      "Office of the Chief of Naval Operations",
      "U.S. Navy Functional Operating Forces",
      "United States Naval Special Warfare Command",

      { type: "separator", label: "DEPARTMENT OF THE AIR FORCE" },
      "Office of the Secretary of the Air Force",
      "Office of the Under Secretary of the Air Force",
      "Office of the Assistant Secretary of the Air Force for Acquisition, Technology and Logistics",
      "Office of the Assistant Secretary of the Air Force for Financial Management and Comptroller",
      "Office of the Assistant Secretary of the Air Force for Installations, Environment and Energy",
      "Office of the Assistant Secretary of the Air Force for Manpower and Reserve Affairs",
      "Office of the General Counsel of the Air Force",
      "Office of the Inspector General of the Air Force",
      "Office of the Administrative Assistant to the Secretary of the Air Force",

      { type: "separator", label: "UNITED STATES SPACE FORCE" },
      "Space Operations Command",
      "Space Training and Readiness Command",
      "Space Systems Command",
      "Space Rapid Capabilities Office",
      "Space Development Agency",
      "Space Warfighting Analysis Center",
    ],
  },
  {
    title: "United States Department of Education",
    agencies: [
      "Office of the Secretary of Education (OSE)",
      "Office of Communications and Outreach",
      "Office of Finance and Operations",
      "Office of Inspector General",
      "Office of the General Counsel",
      "Office of Legislation and Congressional Affairs",
      "Office for Civil Rights",
      "Office of Educational Technology",
      "Office of the Chief Information Officer",
      "Office of Planning, Evaluation and Policy Development",
      "Budget Service",
      "Risk Management Service",
      "Office of Deputy Secretary of Education (ODSE)",

      {
        type: "separator",
        label: "OFFICE OF ELEMENTARY & SECONDARY EDUCATION",
      },
      "Office of Migrant Education",
      "Office of Safe and Healthy Students",
      "Office of English Language Acquisition, Language Enhancement, and Academic Achievement for Limited English Language Proficient Students",

      {
        type: "separator",
        label: "OFFICE OF SPECIAL EDUCATION & REHABILITATIVE SERVICES",
      },
      "Office of Special Education Programs",
      "Rehabilitation Services Administration",

      { type: "separator", label: "INSTITUTE OF EDUCATION SCIENCES (IES)" },
      "National Center for Education Evaluation and Regional Assistance",
      "National Center for Education Research",
      "National Center for Education Statistics",
      "National Center for Special Education Research",
      "National Board for Education Sciences",

      { type: "separator", label: "OFFICE OF THE UNDER SECRETARY (OUS)" },
      "Office of Career, Technical, and Adult Education",
      "Office of Federal Student Aid",
      "Office of Postsecondary Education",

      {
        type: "separator",
        label: "WHITE HOUSE INITIATIVES & OPERATING COMMISSIONS",
      },
      "Center for Faith and Opportunity Initiatives",
      "White House Initiative on Asian Americans and Pacific Islanders",
      "White House Initiative on Educational Excellence for Hispanics",
      "White House Initiative on Historically Black Colleges and Universities",
      "White House Initiative on Educational Excellence for African Americans",
      "White House Initiative on American Indian and Alaskan Native Education",
      "Commission on Presidential Scholars",
      "National Committee on Foreign Medical Education and Accreditation",

      { type: "separator", label: "ADVISORY BODIES" },
      "Historically Black College and Universities Capital Financing Advisory Board",
      "National Advisory Committee on Institutional Quality and Integrity",
      "National Advisory Council on Indian Education",
      "National Board of the Fund for the Improvement of Postsecondary Education",

      { type: "separator", label: "FEDERALLY-AIDED CORPORATIONS" },
      "American Printing House for the Blind",
      "Gallaudet University",
      "Howard University",
      "National Technical Institute for the Deaf",
    ],
  },
  {
    title: "United States Department of Energy",
    agencies: [
      { type: "separator", label: "LEADERSHIP OFFICES" },
      "Office of the Secretary",
      "Office of the Deputy Secretary",
      "Office of the Under Secretary for Infrastructure",
      "Office of the Under Secretary for Science and Innovation",
      "Office of the Under Secretary for Nuclear Security and Administrator of the National Nuclear Security Administration",

      { type: "separator", label: "PROGRAM OFFICES" },
      "Advanced Research Projects Agency-Energy (ARPA-E)",
      "Artificial Intelligence and Technology Office (AITO)",
      "Loan Programs Office",
      "Office of Cybersecurity, Energy Security, and Emergency Response",
      "Office of Electricity",
      "Office of Energy Efficiency and Renewable Energy",
      "Office of Environmental Management",
      "Office of Fossil Energy and Carbon Management",
      "Office of Indian Energy Policy and Programs",
      "Office of Legacy Management",
      "Office of Nuclear Energy",
      "Office of Science",

      { type: "separator", label: "STAFF OFFICES" },
      "Office of Congressional and Intergovernmental Affairs",
      "Office of Economic Impact and Diversity",
      "Office of Enterprise Assessments",
      "Office of Environment, Health, Safety, and Security",
      "Office of Hearings and Appeals",
      "Office of Inspector General",
      "Office of Intelligence and Counterintelligence",
      "Office of International Affairs",
      "Office of Management",
      "Office of Policy",
      "Office of Project Management",
      "Office of Public Affairs",
      "Office of Small and Disadvantaged Business Utilization",
      "Office of Technology Transitions",
      "Office of the Chief Financial Officer",
      "Office of the Chief Human Capital Officer",
      "Office of the Chief Information Officer",
      "Office of the General Counsel",
      "Office of NEPA Policy and Compliance",

      { type: "separator", label: "POWER ADMINISTRATIONS & OTHER AGENCIES" },
      "Federal Energy Regulatory Commission",
      "National Nuclear Security Administration",
      "Energy Information Administration",
      "Bonneville Power Administration",
      "Southeastern Power Administration",
      "Southwestern Power Administration",
      "Western Area Power Administration",

      {
        type: "separator",
        label: "NATIONAL LABORATORIES & TECHNOLOGY CENTERS",
      },
      "Ames Laboratory",
      "Argonne National Laboratory",
      "Brookhaven National Laboratory",
      "Fermi National Accelerator Laboratory",
      "Idaho National Laboratory",
      "Lawrence Berkeley National Laboratory",
      "Lawrence Livermore National Laboratory",
      "Los Alamos National Laboratory",
      "National Energy Technology Laboratory",
      "National Renewable Energy Laboratory",
      "New Brunswick Laboratory",
      "Oak Ridge Institute for Science and Education",
      "Oak Ridge National Laboratory",
      "Pacific Northwest National Laboratory",
      "Princeton Plasma Physics Laboratory",
      "Radiological and Environmental Sciences Laboratory",
      "Sandia National Laboratories",
      "Savannah River Ecology Laboratory",
      "Savannah River National Laboratory",
      "SLAC National Accelerator Laboratory",
      "Thomas Jefferson National Accelerator Facility",

      { type: "separator", label: "FIELD SITES" },
      "Carlsbad Field Office",
      "Environmental Management Los Alamos Field Office",
      "Golden Field Office",
      "Idaho Operations Office",
      "Oak Ridge Office of Environmental Management",
      "Office of River Protection",
      "Portsmouth/Paducah Project Office",
      "Richland Operations Office",
      "Savannah River Operations Office",
      "Office of Science Field Offices",
      "Pacific Northwest Site Office",
    ],
  },
  {
    title: "United States Department of Health and Human Services",
    agencies: [
      { type: "separator", label: "OFFICE OF THE SECRETARY (OS)" },
      "Immediate Office of the Secretary (IOS)",
      "Office of the Assistant Secretary for Administration",
      "Program Support Center",
      "Office of the Assistant Secretary for Financial Resources",
      "Office of the Assistant Secretary for Legislation",
      "Office of the Assistant Secretary for Planning and Evaluation",
      "Office of the Assistant Secretary for Public Affairs",
      "Office of the Assistant Secretary for Health",
      "Office of the Assistant Secretary for Preparedness and Response",
      "Biomedical Advanced Research and Development Authority",
      "Center for Faith and Opportunity Initiative",
      "Departmental Appeals Board",
      "Office for Civil Rights",
      "Office of Global Affairs",
      "Office of Inspector General",
      "Office of Intergovernmental and External Affairs",
      "Office of Medicare Hearings and Appeals",
      "Office of the Chief Technology Officer",
      "Office of the General Counsel",
      "Office of the National Coordinator for Health Information Technology",

      { type: "separator", label: "ADMINISTRATION & CHILD SERVICES" },
      "Administration on Aging",
      "Administration for Children and Families",
      "Administration for Native Americans",
      "Administration on Developmental Disabilities",
      "Office of Child Care",
      "Office of Child Support Enforcement",
      "Children's Bureau",
      "National Center on Child Abuse and Neglect",
      "Family and Youth Services Bureau",
      "Office of Head Start",
      "Office of Community Services",
      "Office of Family Assistance",
      "Office of Refugee Resettlement",
      "President's Committee for People with Intellectual Disabilities",

      { type: "separator", label: "AGENCIES & RESEARCH" },
      "Agency for Healthcare Research and Quality",
      "Centers for Disease Control and Prevention (CDC)",
      "Center for Surveillance, Epidemiology and Laboratory Services (CSELS)",
      "Division of Health Informatics and Surveillance",
      "Division of Laboratory Systems",
      "Division of Public Health Information Dissemination",
      "Division of Scientific Education and Professional Development",
      "CDC Washington Office",
      "Center for Global Health",
      "National Institute for Occupational Safety and Health",
      "Advisory Committee on Immunization Practices",
      "National Center for Health Statistics",
      "National Vital Statistics System",
      "Office for State, Tribal, Local and Territorial Support",
      "Office of Equal Employment Opportunity",

      { type: "separator", label: "CDC - DISEASE PREVENTION & RESPONSE" },
      "Office of Infectious Diseases",
      "National Center for Emerging and Zoonotic Infectious Diseases",
      "Division of High-Consequence Pathogens and Pathology (DHCPP)",
      "Viral Special Pathogens Branch (VSPB)",
      "National Center for HIV/AIDS, Viral Hepatitis, STD, and TB Prevention",
      "National Center for Immunization and Respiratory Diseases",
      "Office of Minority Health and Health Equity",
      "Office of Noncommunicable Diseases, Injury and Environmental Health",
      "National Center for Chronic Disease Prevention and Health Promotion",
      "National Center for Environmental Health/Agency for Toxic Substances and Disease Registry",
      "National Center for Injury Prevention and Control",
      "National Center on Birth Defects and Developmental Disabilities",
      "Office of Public Health Preparedness and Response",
      "Division of Emergency Operations",
      "Emergency Operations Center (EOC)",

      { type: "separator", label: "HEALTHCARE & MEDICAL SERVICES" },
      "Centers for Medicare and Medicaid Services",
      "Food and Drug Administration (FDA)",
      "National Center for Food Safety and Applied Nutrition",
      "Office of Criminal Investigations",
      "Health Resources and Services Administration",
      "Patient Affordable Healthcare Act Program",
      "Independent Payment Advisory Board",
      "Indian Health Service",

      { type: "separator", label: "NATIONAL INSTITUTES OF HEALTH (NIH)" },
      "National Institutes of Health Police",
      "National Cancer Institute",
      "National Eye Institute",
      "National Heart, Lung, and Blood Institute",
      "Rocky Mountain Laboratories",
      "National Human Genome Research Institute",
      "National Institute on Aging",
      "National Institute on Alcohol Abuse and Alcoholism",
      "National Institute of Allergy and Infectious Diseases",
      "National Institute of Arthritis and Musculoskeletal and Skin Diseases",
      "National Institute of Biomedical Imaging and Bioengineering",
      "National Institute of Child Health and Human Development",
      "National Institute on Deafness and Other Communication Disorders",
      "National Institute of Dental and Craniofacial Research",
      "National Institute of Diabetes and Digestive and Kidney Diseases",
      "National Institute on Drug Abuse",
      "National Institute of Environmental Health Sciences",
      "National Institute of General Medical Sciences",
      "National Institute of Mental Health",
      "National Institute on Minority Health and Health Disparities",
      "National Institute of Neurological Disorders and Stroke",
      "National Institute of Nursing Research",
      "Center for Information Technology",
      "Center for Scientific Review",
      "Fogarty International Center",
      "National Center for Advancing Translational Sciences",
      "National Center for Complementary and Integrative Health",
      "NIH Clinical Center",

      { type: "separator", label: "PUBLIC HEALTH SERVICE" },
      "Federal Occupational Health",
      "Office of the Surgeon General",
      "United States Public Health Service Commissioned Corps",
      "Substance Abuse and Mental Health Services Administration",
    ],
  },
  {
    title: "United States Department of Homeland Security",
    agencies: [
      { type: "separator", label: "OFFICE OF THE SECRETARY" },
      "Office of the Secretary",
      "Immediate Office of the Secretary",
      "Office of the Deputy Secretary",
      "Office of the Chief of Staff",
      "Military Advisor's Office",
      "Office of the Executive Secretary",
      "Joint Requirements Council",
      "Office of Strategy, Policy, and Plans",
      "Office of Immigration Statistics",
      "Office of International Affairs",
      "Office of General Counsel",
      "Office of Legislative Affairs",
      "Office of Public Affairs",
      "Office of Partnership and Engagement",
      "Homeland Security Advisory Council",
      "Office of State and Local Law Enforcement",
      "Private Sector Office",
      "Office for Civil Rights and Civil Liberties",
      "Office of the Citizenship and Immigration Services Ombudsman",
      "Office of the Immigration Detention Ombudsman",
      "Privacy Office",

      { type: "separator", label: "HEADQUARTERS OFFICES & DIRECTORATES" },
      "Management Directorate",
      "Federal Protective Service",
      "Office of Biometric Identity Management",
      "Office of the Chief Financial Officer",
      "Office of the Chief Information Officer",
      "Office of the Chief Human Capital Officer",
      "Office of the Chief Procurement Officer",
      "Office of the Chief Readiness Support Officer",
      "Canine and Equine Governance Board",
      "Office of the Chief Security Officer",
      "Science and Technology Directorate",
      "Office of Intelligence and Analysis",
      "Current and Emerging Threats Center",
      "Homeland Identities, Targeting and Exploitation Center",
      "Transnational Organized Crime Mission Center",
      "Counterterrorism Mission Center",
      "Counterintelligence Mission Center",
      "Cyber Mission Center",
      "Economic Security Mission Center",
      "Office of Operations Coordination",
      "National Operations Center",
      "Countering Weapons of Mass Destruction Office",
      "Chief Medical Officer",
      "Office of Inspector General",

      { type: "separator", label: "COMPONENT AGENCIES" },
      "Federal Emergency Management Agency (FEMA)",
      "United States Fire Administration",
      "National Flood Insurance Program",
      "Center for Domestic Preparedness",
      "Emergency Management Institute",
      "Mount Weather Emergency Operations Center",
      "Federal Insurance and Mitigation Administration",

      {
        type: "separator",
        label: "CYBERSECURITY & INFRASTRUCTURE SECURITY AGENCY (CISA)",
      },
      "Cybersecurity Division",
      "National Cybersecurity and Communications Integration Center",
      "National Council of Statewide Interoperability Coordinators (NCSWIC)",
      "Infrastructure Security Division",
      "Emergency Communications Division",
      "National Risk Management Center",
      "Integrated Operations Division",
      "Stakeholder Engagement Division",
      "National Emergency Technology Guard (Inactive, but can be activated by the Director of CISA)",

      { type: "separator", label: "FEDERAL LAW ENFORCEMENT TRAINING CENTERS" },
      "Transportation Security Administration (TSA)",
      "Federal Air Marshal Service",
      "United States Citizenship and Immigration Services",

      { type: "separator", label: "UNITED STATES COAST GUARD" },
      "Coast Guard Intelligence",
      "Coast Guard Investigative Service",
      "United States Coast Guard Police",
      "United States Coast Guard Yard",
      "United States Coast Guard Research and Development Center",
      "United States Coast Guard Academy",
      "United States Coast Guard Training Center Cape May",
      "United States Coast Guard Reserve",
      "United States Coast Guard Auxiliary",
      "National Ice Center",

      { type: "separator", label: "UNITED STATES CUSTOMS & BORDER PROTECTION" },
      "Air and Marine Operations",
      "United States Border Patrol",
      "Office of Field Operations",
      "Office of Trade",

      {
        type: "separator",
        label: "UNITED STATES IMMIGRATION & CUSTOMS ENFORCEMENT (ICE)",
      },
      "Enforcement and Removal Operations",
      "Homeland Security Investigations",
      "Office of Professional Responsibility",
      "Office of the Principal Legal Advisor",

      { type: "separator", label: "UNITED STATES SECRET SERVICE" },
      "United States Secret Service Uniformed Division",
      "James J. Rowley Training Center",
    ],
  },
  {
    title: "United States Department of Justice",
    agencies: [
      { type: "separator", label: "LEADERSHIP OFFICES" },
      "Office of the Attorney General",
      "Office of the Deputy Attorney General",
      "Office of the Associate Attorney General",
      "Office of the Solicitor General",
      "Special Counsel's Office",

      { type: "separator", label: "DIVISIONS" },
      "Antitrust Division",
      "Civil Division",
      "Civil Rights Division",
      "Criminal Division",
      "Environment and Natural Resources Division",
      "Justice Management Division",
      "Asset Forfeiture Fund",
      "National Security Division",
      "Tax Division",

      { type: "separator", label: "LAW ENFORCEMENT AGENCIES" },
      "Bureau of Alcohol, Tobacco, Firearms and Explosives (ATF)",
      "Bureau of Prisons",
      "Federal Prison Industries (aka Unicor)",
      "National Institute of Corrections",
      "Community Relations Service",
      "Drug Enforcement Administration",
      "El Paso Intelligence Center",
      "Office of National Security Intelligence",
      "Federal Bureau of Investigation (FBI)",
      "Intelligence Branch",
      "National Security Branch",
      "Counterterrorism Division",
      "Criminal, Cyber, Response, and Services Branch",
      "Critical Incident Response Group",
      "National Center for the Analysis of Violent Crime",
      "Strategic Information and Operations Center",
      "Crisis Negotiation Unit",
      "Behavioral Analysis Unit",
      "Science and Technology Branch",
      "FBI Laboratory",
      "FBI Criminal Justice Information Services Division",
      "Information and Technology Branch",
      "Human Resources Branch",
      "FBI Academy",
      "National Gang Intelligence Center",
      "INTERPOL Washington – United States National Central Bureau",
      "United States Marshals Service",
      "Justice Prisoner and Alien Transportation System",

      { type: "separator", label: "EXECUTIVE & LEGAL OFFICES" },
      "Executive Office for Immigration Review",
      "Board of Immigration Appeals",
      "Executive Office for Organized Crime Drug Enforcement Task Forces",
      "Executive Office for United States Attorneys",
      "Executive Office for United States Trustees",
      "Foreign Claims Settlement Commission of the United States",
      "Office of Community Oriented Policing Services",
      "Office of Justice Programs",
      "Bureau of Justice Assistance",
      "Bureau of Justice Statistics",
      "National Criminal Justice Reference Service",
      "National Institute of Justice",
      "Office for Victims of Crime",
      "Office of Juvenile Justice and Delinquency Prevention",
      "Office of Sex Offender Sentencing, Monitoring, Apprehending, Registering, and Tracking (SMART)",
      "Office of Legal Counsel",
      "Office of Legal Policy",
      "Office of the Pardon Attorney",
      "Office on Violence Against Women",
      "Offices of the United States Attorneys",
      "United States Parole Commission",

      { type: "separator", label: "SUPPORT & OVERSIGHT OFFICES" },
      "Office of Information Policy",
      "Office of Legislative Affairs",
      "Office of Public Affairs",
      "Office of Professional Responsibility",
      "Office of the Inspector General",
      "Office of Tribal Justice",
      "Professional Responsibility Advisory Office",
    ],
  },
  {
    title: "United States Department of Labor",
    agencies: [
      { type: "separator", label: "LEADERSHIP OFFICES" },
      "Office of the Secretary (OSEC)",
      "Executive Secretary",
      "Centers for Faith and Opportunity Initiative",
      "Office of the Ombudsman for the Energy Employees Occupational Illness Programs",
      "Office of Public Liaison",

      { type: "separator", label: "OFFICES UNDER THE DEPUTY SECRETARY" },
      "Office of the Assistant Secretary for Administration and Management",
      "Office of the Assistant Secretary for Policy",
      "Office of the Chief Financial Officer",
      "Office of the Chief Information Officer",
      "Office of Congressional and Intergovernmental Affairs",
      "Office of Emergency Management",
      "Office of Federal Contract Compliance Programs",
      "Office of Labor-Management Standards",
      "Office of Public Affairs",
      "Office of Disability Employment Policy",
      "Office of the Solicitor",
      "Office of Worker's Compensation Program",

      { type: "separator", label: "ADMINISTRATIONS" },
      "Employee Benefits Security Administration",
      "Employment and Training Administration",
      "Mine Safety and Health Administration",
      "Occupational Safety and Health Administration",

      {
        type: "separator",
        label: "BOARDS UNDER THE OFFICE OF ADMINISTRATIVE LAW JUDGES",
      },
      "Administrative Review Board",
      "Benefits Review Board",
      "Employees' Compensation Appeals Board",

      { type: "separator", label: "BUREAUS" },
      "Bureau of International Labor Affairs",
      "Bureau of Labor Statistics",
      "Women's Bureau",

      { type: "separator", label: "MISCELLANEOUS" },
      "National Labor Library",
      "Veterans' Employment and Training Service",
      "Wage and Hour Division",
      "Wirtz Labor Library",
    ],
  },
  {
    title: "United States Department of State",
    agencies: [
      { type: "separator", label: "OFFICE OF THE SECRETARY" },
      "Office of the Secretary",
      "Chief of Staff",
      "Bureau of Intelligence and Research",
      "Bureau of Legislative Affairs",
      "Office of the Legal Adviser",
      "Executive Secretariat",
      "Operations Center",
      "Executive Secretariat Staff",
      "Advance and Staffing Division",
      "Records and Information Management Division",
      "Executive Office of the Executive Secretariat",
      "ExecTech Office",
      "Office of the Chief of Protocol",
      "Counselor of the Department",
      "Office of the United States Global AIDS Coordinator and Health Diplomacy",
      "Policy Planning Staff",
      "Secretary's Foreign Affairs Policy Board",
      "Office of Civil Rights",
      "Office of the Ombudsman",
      "Ombuds Services Office",
      "Workplace Conflict Prevention and Resolution Center (wCPRc)",
      "Foreign Service Grievance Board",
      "Secretary's Open Forum",
      "Office of Hostage Affairs",
      "Office of Global Women's Issues",
      "Office of the Coordinator for Cyber Issues",
      "Office of the Special Presidential Envoy for the Global Coalition to Defeat ISIS",
      "Office of Inspector General",
      "Iran Action Group",
      "Special Representative for Afghanistan Reconciliation",
      "Special Representative for Syria Engagement",
      "Special Representative for Venezuela",
      "United States Security Coordinator for Israel and the Palestinian Authority",

      {
        type: "separator",
        label: "DEPUTY SECRETARY FOR MANAGEMENT AND RESOURCES",
      },
      "Office of Foreign Assistance",

      {
        type: "separator",
        label: "UNDER SECRETARY FOR ARMS CONTROL AND INTERNATIONAL SECURITY",
      },
      "Bureau of Arms Control, Verification, and Compliance",
      "Bureau of International Security and Nonproliferation",
      "Bureau of Political-Military Affairs",
      "Office of Weapons Removal and Abatement",
      "International Security Advisory Board",

      {
        type: "separator",
        label:
          "UNDER SECRETARY FOR HUMAN RIGHTS, CIVILIAN SECURITY, AND DEMOCRACY",
      },
      "Bureau of Conflict and Stabilization Operations",
      "Bureau of Counterterrorism",
      "Bureau of Democracy, Human Rights, and Labor",
      "Bureau of International Narcotics and Law Enforcement Affairs",
      "Office of Aviation",
      "Bureau of Population, Refugees, and Migration",
      "Office of Global Criminal Justice",
      "Office to Monitor and Combat Trafficking in Persons",
      "Office of International Religious Freedom",
      "Office of the Special Envoy to Monitor and Combat Anti-Semitism",
      "Office of the U.S. Special Coordinator for Tibetan Issues",

      {
        type: "separator",
        label: "UNDER SECRETARY FOR ENVIRONMENT, ENERGY, AND ECONOMIC GROWTH",
      },
      "Bureau of Economic and Business Affairs",
      "Bureau of Energy Resources",
      "Bureau of Oceans and International Environmental and Scientific Affairs",
      "Office of the Chief Economist",
      "Office of Global Partnerships",
      "Office of the Science and Technology Advisor to the Secretary",

      { type: "separator", label: "UNDER SECRETARY FOR MANAGEMENT" },
      "Bureau of Administration",
      "Bureau of Budget and Planning",
      "Bureau of the Comptroller and Global Financial Services",
      "Bureau of Information Resource Management",
      "Diplomatic Telecommunications Service",
      "Bureau of Global Talent Management",
      "Office of the Director General of the Foreign Service and Director of Global Talent",
      "Foreign Service Institute",
      "Bureau of Consular Affairs",
      "Bureau of Diplomatic Security (DS)",
      "Diplomatic Security Service (DSS)",
      "Diplomatic Courier Service",
      "Rewards for Justice Program",
      "Bureau of Overseas Buildings Operations",
      "Office of Foreign Missions (OFM)",
      "Bureau of Medical Services",
      "Office of Management Strategy and Solutions",
      "Director of Diplomatic Reception Rooms",
      "Office of the White House Liaison",

      { type: "separator", label: "UNDER SECRETARY FOR POLITICAL AFFAIRS" },
      "Bureau of African Affairs",
      "Bureau of East Asian and Pacific Affairs",
      "Bureau of European and Eurasian Affairs",
      "Bureau of International Organization Affairs",
      "Bureau of Near Eastern Affairs",
      "Bureau of South and Central Asian Affairs",
      "Bureau of Western Hemisphere Affairs",

      {
        type: "separator",
        label: "UNDER SECRETARY FOR PUBLIC DIPLOMACY AND PUBLIC AFFAIRS",
      },
      "Bureau of Educational and Cultural Affairs",
      "Bureau of Global Public Affairs",
      "Office of Policy, Planning and Resources for Public Affairs and Public Diplomacy",
      "Global Engagement Center",
      "International Expositions Unit",
      "United States Advisory Commission on Public Diplomacy",

      { type: "separator", label: "PERMANENT DIPLOMATIC MISSIONS" },
      "United States Mission to the African Union",
      "United States Mission to the Association of Southeast Asian Nations",
      "United States Mission to the Arab League",
      "United States Mission to the Council of Europe (and to all other European Agencies)",
      "United States Mission to International Organizations in Vienna",
      "United States Mission to the European Union",
      "United States Mission to the International Civil Aviation Organization",
      "United States Mission to the North Atlantic Treaty Organization",
      "United States Mission to the Organisation for Economic Co-operation and Development",
      "United States Mission to the Organization of American States",
      "United States Mission to the Organization for Security and Cooperation in Europe",
      "United States Mission to the United Nations",
      "United States Mission to the UN Agencies in Rome",
      "United States Mission to the United Nations Office and Other International Organizations in Geneva",
      "United States Observer Mission to the United Nations Educational, Scientific, and Cultural Organization",
      "United States Permanent Mission to the United Nations Environment Programme and the United Nations Human Settlements Programme",
    ],
  },
  {
    title: "United States Department of Transportation",
    agencies: [
      { type: "separator", label: "OPERATING ADMINISTRATIONS" },
      "Office of the Secretary",
      "Immediate Office of the Secretary of Transportation",
      "Office of the Deputy Secretary",
      "Office of the Under Secretary of Transportation for Policy",
      "Office of the Assistant Secretary for Transportation Policy",
      "Office of the Chief Economist",
      "Infrastructure Permitting Improvement Center",
      "Office of the Assistant Secretary for Research and Technology",
      "Bureau of Transportation Statistics",
      "National Transportation Library",
      "John A. Volpe National Transportation Systems Center",
      "Office of the Assistant Secretary for Aviation and International Affairs",
      "National Surface Transportation and Innovative Finance Bureau",
      "Office of the Executive Secretariat",
      "Office of Intelligence, Security, and Emergency Response",
      "Office of the Chief Information Officer",
      "Office of Public Affairs",
      "Office of Public Engagement",
      "Office of the Chief Financial Officer and Assistant Secretary for Budget and Programs",
      "Office of the General Counsel",
      "Office of the Assistant Secretary for Governmental Affairs",
      "Office of Tribal Government Affairs",
      "Office of the Assistant Secretary for Administration",
      "Office of Hearings",
      "Departmental Office of Civil Rights",
      "Advisory Committee on Transportation Equity",
      "Office of Small and Disadvantaged Business Utilization",
      "Office of Drug and Alcohol Policy and Compliance",
      "Office of Inspector General",

      { type: "separator", label: "FEDERAL AGENCIES AND ADMINISTRATIONS" },
      "Federal Aviation Administration",
      "Federal Highway Administration",
      "Federal Motor Carrier Safety Administration",
      "Federal Railroad Administration",
      "Federal Transit Administration",
      "Great Lakes St. Lawrence Seaway Development Corporation",
      "Maritime Administration",
      "United States Merchant Marine Academy",
      "National Highway Traffic Safety Administration",
      "Pipeline and Hazardous Materials Safety Administration",
    ],
  },
  {
    title: "United States Department of the Treasury",
    agencies: [
      { type: "separator", label: "DEPARTMENTAL OFFICES" },
      "Office of the Secretary",
      "Office of the Deputy Secretary",
      "Office of the Chief of Staff",
      "Office of Inspector General",
      "Office of General Counsel",
      "Office of Legislative Affairs",
      "Office of Management",
      "Office of Public Affairs",
      "Office of Domestic Finance",
      "Office of Financial Institutions",
      "Community Development Financial Institutions Fund",
      "Financial Stability Oversight Council",
      "Office of Financial Research",
      "Terrorism Risk Insurance Program",
      "Small Business Lending Fund",
      "Federal Insurance Office",
      "Office of Financial Markets",
      "Federal Financing Bank",
      "Office of Fiscal Service",
      "Office of Financial Stability",
      "Office of Economic Policy",
      "Office of International Affairs",
      "Committee on Foreign Investment in the United States",
      "Office of Technical Assistance",
      "Office of Tax Policy",
      "Office of Terrorism and Financial Intelligence",
      "Office of Foreign Assets Control",
      "Office of Intelligence and Analysis",
      "Office of Terrorist Financing and Financial Crimes",
      "Treasury Executive Office for Asset Forfeiture",
      "Office of the Treasurer of the United States",

      { type: "separator", label: "BUREAUS" },
      "Alcohol and Tobacco Tax and Trade Bureau",
      "Bureau of Engraving and Printing",
      "Bureau of the Fiscal Service",
      "Financial Crimes Enforcement Network",
      "Internal Revenue Service (IRS)",
      "Office of the Comptroller of the Currency",
      "Office of the Treasury Inspector General for Tax Administration",
      "Office of the Special Inspector General for Pandemic Recovery",
      "Office of the Special Inspector General for the Troubled Asset Relief Program",
      "United States Mint",
    ],
  },
  {
    title: "United States Department of Veterans Affairs",
    agencies: [
      { type: "separator", label: "OFFICE OF THE SECRETARY" },
      "Office of the Secretary of Veterans Affairs",
      "Office of General Counsel",
      "Office of Management",
      "Office of Human Resources and Administration/Operations, Security, and Preparedness",
      "Office of Information and Technology",
      "Office of Enterprise Integration",
      "Office of Public and Intergovernmental Affairs",
      "Office of Congressional and Legislative Affairs",
      "Office of Acquisition, Logistics, and Construction",
      "Office of Accountability and Whistleblower Protection",
      "Veterans Experience Office",
      "Office of Electronic Health Record Modernization",
      "Office of Inspector General",

      { type: "separator", label: "AGENCIES" },
      "Board of Veterans' Appeals (BVA)",
      "National Cemetery Administration (NCA)",
      "Veterans Benefits Administration (VBA)",
      "Veterans Health Administration (VHA)",
    ],
  },
  {
    title: "Independent Agencies, Tribunals, and Government-Owned Corporations",
    agencies: [
      {
        type: "separator",
        label: "ADMINISTRATION, RECORDS, AND FEDERAL PROPERTY",
      },
      "Administrative Conference of the United States",
      "General Services Administration (GSA)",
      "Federal Systems Integration and Management Center",
      "USAGov",
      "Office of the President-Elect",
      "National Archives and Records Administration (NARA)",
      "Information Security Oversight Office",
      "Public Interest Declassification Board",
      "Office of the Federal Register",
      "Office of Presidential Libraries",

      { type: "separator", label: "CIVIL RIGHTS" },
      "Commission on Civil Rights",
      "Equal Employment Opportunity Commission (EEOC)",
      "National Council on Disability",

      { type: "separator", label: "CIVIL SERVICE" },
      "Merit Systems Protection Board (MSPB)",
      "Office of Government Ethics (OGE)",
      "Office of Personnel Management (OPM)",
      "Human Resources University",
      "USOPM Office of the Inspector General",
      "Federal Executive Institute",
      "Chief Acquisition Officers Council",
      "Chief Human Capital Officers Council",
      "Chief Financial Officers Council",
      "Chief Information Officers Council",
      "Office of Special Counsel (OSC)",

      { type: "separator", label: "COMMERCE" },
      "Federal Trade Commission (FTC)",
      "FTC Office of the Inspector General",
      "Consumer Product Safety Commission (CPSC)",
      "CPSC Office of the Inspector General",
      "Federal Communications Commission (FCC)",
      "Universal Service Fund",
      "Radio Amateur Civil Emergency Service",
      "Federal Housing Finance Agency",
      "Federal Housing Finance Board",
      "United States International Trade Commission",

      { type: "separator", label: "DEFENSE AND SECURITY" },
      "Court of Appeals for the Armed Forces",
      "Central Intelligence Agency (CIA)",
      "Central Intelligence Agency Security Protective Service",
      "Defense Nuclear Facilities Safety Board",
      "Office of the Director of National Intelligence (ODNI)",
      "National Intelligence Board",
      "Office of the National Counterintelligence Executive",
      "Intelligence Advanced Research Projects Activity",
      "National Security Commission on Artificial Intelligence",
      "Selective Service System",

      { type: "separator", label: "ELECTIONS" },
      "Election Assistance Commission (EAC)",
      "EAC Office of Inspector General",
      "Federal Election Commission (FEC)",
      "FEC Office of Inspector General",

      { type: "separator", label: "EDUCATION AND BROADCASTING" },
      "Corporation for Public Broadcasting (CPB)",
      "Public Broadcasting Service (PBS)",
      "National Public Radio (NPR)",
      "Helen Keller National Center",
      "Institute of Museum and Library Services",
      "U.S. Agency for Global Media (USAGM)",
      "Voice of America (VOA)",
      "Radio Free Europe/Radio Liberty (RFE/RL)",
      "Radio y Television Marti",
      "Radio Free Asia (RFA)",
      "Middle Eastern Broadcasting Networks",
      "International Broadcasting Bureau",
      "National Endowment for the Arts (NEA)",
      "National Endowment for the Humanities (NEH)",

      { type: "separator", label: "ENERGY AND SCIENCE" },
      "National Aeronautics and Space Administration (NASA)",
      "National Science Board",
      "National Science Foundation (NSF)",
      "National Center for Science and Engineering Statistics",
      "University Corporation for Atmospheric Research",
      "National Center for Atmospheric Research",
      "United States Antarctic Program",
      "United States Arctic Research Commission",
      "Nuclear Regulatory Commission (NRC)",
      "Office of the Federal Coordinator, Alaska Natural Gas Transportation Projects",
      "Tennessee Valley Authority (TVA)",
      "Tennessee Valley Authority Police",

      { type: "separator", label: "MONETARY AND FINANCIAL" },
      "Commodity Futures Trading Commission (CFTC)",
      "Court of Appeals for Veterans Claims",
      "Court of Federal Claims",
      "Farm Credit Administration",
      "Federal Reserve System",
      "Federal Reserve Police",
      "Consumer Financial Protection Bureau (CFPB)",
      "Federal Reserve Bank of Boston",
      "Federal Reserve Bank of New York",
      "Federal Reserve Bank of Philadelphia",
      "Federal Reserve Bank of Richmond",
      "Federal Reserve Bank of Atlanta",
      "Federal Reserve Bank of Chicago",
      "Federal Reserve Bank of St. Louis",
      "Federal Reserve Bank of Minneapolis",
      "Federal Reserve Bank of Kansas City",
      "Federal Reserve Bank of Dallas",
      "Federal Reserve Bank of San Francisco",
      "Federal Deposit Insurance Corporation (FDIC)",
      "National Credit Union Administration (NCUA)",
      "Central Liquidity Facility",
      "Securities and Exchange Commission (SEC)",
      "Securities Investor Protection Corporation",
      "Small Business Administration (SBA)",
      "United States Tax Court",

      { type: "separator", label: "POSTAL" },
      "Postal Regulatory Commission (PRC)",
      "United States Postal Service (USPS)",
      "United States Postal Inspection Service (USPIS)",
      "US Postal Service Police",
      "Citizens' Stamp Advisory Committee",
      "USPS Office of the Inspector General",
      "US Philatelic Bureau",
      "US Stamp Printing Service",

      { type: "separator", label: "RETIREMENT" },
      "Federal Retirement Thrift Investment Board",
      "Thrift Savings Plan (TSP)",
      "Railroad Retirement Board",
      "Social Security Administration (SSA)",

      { type: "separator", label: "TRANSPORTATION" },
      "Amtrak (National Railroad Passenger Corporation)",
      "Amtrak Police",
      "Federal Maritime Commission",
      "National Transportation Safety Board (NTSB)",
      "Surface Transportation Board (STB)",

      { type: "separator", label: "VOLUNTEERISM" },
      "Corporation for National and Community Service",
      "AmeriCorps",
      "AmeriCorps Organizations",
      "AmeriCorps VISTA",
      "Senior Corps",
      "Learn and Serve America",
      "National Civilian Community Corps",
      "Volunteers in Service to America",
      "USA Freedom Corps",
      "Presidential Freedom Scholarship Program",
      "President's Volunteer Service Award",
      "Peace Corps",
    ],
  },
  {
    title: "Joint Programs and Interagency Agencies",
    agencies: [
      { type: "separator", label: "JOINT PROGRAMS AND INTERAGENCY AGENCIES" },
      "Committee for the Implementation of Textile Agreements",
      "Federal Financial Institutions Examination Council",
      "Federal Interagency Committee on Education",
      "Federal Interagency Council on Statistical Policy",
      "Federal Interagency Committee for the Management of Noxious and Exotic Weeds",
      "Interagency Alternative Dispute Resolution Working Group",
      "Joint Fire Science Program",
      "National Interagency Fire Center",
      "United States Interagency Council on Homelessness",
    ],
  },
  {
    title: "Special Inspector General Office",
    agencies: [
      { type: "separator", label: "SPECIAL INSPECTOR GENERAL OFFICE" },
      "Special Inspector General for Afghanistan Reconstruction",
    ],
  },
  {
    title: "Quasi-Official Agencies",
    agencies: [
      { type: "separator", label: "ARTS & CULTURAL AGENCIES" },
      "Corporation for Travel Promotion",
      "John F. Kennedy Center for the Performing Arts",
      "National Gallery of Art",
      "Smithsonian Institution",
      "Smithsonian Police (Smithsonian Institution Office of Protection Services)",
      "National Zoological Police",
      "U.S. National Museum",
      "U.S. National Zoo",
      "U.S. National Theater",
      "Woodrow Wilson International Center for Scholars",

      { type: "separator", label: "MUSEUM AGENCIES" },
      "United States Holocaust Memorial Museum",

      { type: "separator", label: "COMMERCE & TECHNOLOGY AGENCIES" },
      "North American Electric Reliability Corporation",
      "Municipal Securities Rulemaking Board",
      "National Futures Association",
      "Public Company Accounting Oversight Board",
      "Financial Industry Regulatory Authority",
      "Federal National Mortgage Association (Fannie Mae)",
      "Federal Home Loan Mortgage Corporation (Freddie Mac)",
      "Federal Home Loan Banks",
      "Farm Credit System",
      "U.S. Civilian Research & Development Foundation",

      { type: "separator", label: "DEFENSE & DIPLOMACY AGENCIES" },
      "American Institute in Taiwan",
      "East–West Center",
      "Millennium Challenge Corporation",
      "National Endowment for Democracy",
      "United States Institute of Peace",
      "Henry M. Jackson Foundation for the Advancement of Military Medicine",

      {
        type: "separator",
        label: "HUMAN SERVICE & COMMUNITY DEVELOPMENT AGENCIES",
      },
      "National Industries for the Blind",
      "Neighborhood Reinvestment Corporation",
      "Access Board",
      "AbilityOne Commission",
      "National Institute of Building Sciences",

      { type: "separator", label: "INTERIOR AGENCIES" },
      "National Fish and Wildlife Foundation",
      "National Park Foundation",

      { type: "separator", label: "LAW & JUSTICE AGENCIES" },
      "Legal Services Corporation",
      "State Justice Institute",
      "Vera Institute of Justice",
      "National Center for Missing & Exploited Children",
    ],
  },
];

const AgencySelectionScreen = () => {
  const [expandedCategory, setExpandedCategory] = useState<string | null>(null);

  const toggleCategory = (title: string) => {
    setExpandedCategory(expandedCategory === title ? null : title);
  };

  return (
    <SafeAreaView style={styles.safeContainer}>
      <Header />
      <View style={styles.container}>
        <Text style={styles.title}>Select an Agency</Text>
        <FlatList
          data={categories}
          keyExtractor={(item) => item.title}
          renderItem={({ item }) => (
            <View>
              <TouchableOpacity
                style={styles.categoryContainer}
                onPress={() => toggleCategory(item.title)}
              >
                <Text style={styles.categoryText}>{item.title}</Text>
                <AntDesign
                  name={expandedCategory === item.title ? "down" : "right"}
                  size={18}
                  color="#fff"
                />
              </TouchableOpacity>
            </View>
          )}
        />
      </View>
      <Footer />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  container: {
    flex: 1,
    paddingHorizontal: 15,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
    marginVertical: 10,
  },
  categoryContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#222",
    padding: 15,
    marginVertical: 5,
    borderRadius: 5,
  },
  categoryText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
});

export default AgencySelectionScreen;
